INFO: 2021-05-26 18:31:52,431  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-26 18:31:52,579  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-26 18:31:52,608  django.request  WARNING: Not Found: /memacc/login/jquery.js
INFO: 2021-05-26 18:31:55,059  dev  INFO: Main page was invited
INFO: 2021-05-26 18:31:55,107  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:32:06,449  django.request  ERROR: Internal Server Error: /memacc/edit/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py", line 35, in edit
    logger.info(f"{user_form.cleaned_data['username']}'s profile was edited")
KeyError: 'username'
INFO: 2021-05-26 18:33:23,224  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-26 18:34:05,941  django.request  ERROR: Internal Server Error: /memacc/edit/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py", line 35, in edit
    logger.info(f"{profile_form.cleaned_data['first_name']}'s profile was edited")
KeyError: 'first_name'
INFO: 2021-05-26 18:34:30,757  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-26 18:34:35,628  dev  INFO: Nastiona's profile was edited
INFO: 2021-05-26 18:34:51,139  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-26 18:34:54,815  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-26 18:35:06,758  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-26 18:53:04,460  dev  INFO: Main page was invited
INFO: 2021-05-26 18:53:04,500  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:54:06,630  dev  INFO: Main page was invited
INFO: 2021-05-26 18:54:06,671  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:54:22,843  dev  INFO: Main page was invited
INFO: 2021-05-26 18:54:22,883  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:55:22,336  dev  INFO: Main page was invited
INFO: 2021-05-26 18:55:22,381  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:57:19,110  dev  INFO: Main page was invited
INFO: 2021-05-26 18:57:19,144  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:57:37,253  dev  INFO: Main page was invited
INFO: 2021-05-26 18:57:37,301  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:58:51,289  dev  INFO: Main page was invited
INFO: 2021-05-26 18:58:51,326  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:59:06,764  dev  INFO: Main page was invited
INFO: 2021-05-26 18:59:06,797  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 18:59:22,869  dev  INFO: Main page was invited
INFO: 2021-05-26 18:59:22,912  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:03:19,383  dev  INFO: Main page was invited
INFO: 2021-05-26 19:03:19,423  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:07:01,864  dev  INFO: Main page was invited
INFO: 2021-05-26 19:07:01,900  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:07:35,453  dev  INFO: Main page was invited
INFO: 2021-05-26 19:07:35,480  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:08:12,014  dev  INFO: Main page was invited
INFO: 2021-05-26 19:08:12,040  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:09:42,560  dev  INFO: Main page was invited
INFO: 2021-05-26 19:09:42,599  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:11:48,601  dev  INFO: Main page was invited
INFO: 2021-05-26 19:11:48,623  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:12:18,848  dev  INFO: Main page was invited
INFO: 2021-05-26 19:12:18,878  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:13:52,066  dev  INFO: Main page was invited
INFO: 2021-05-26 19:13:52,091  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:14:09,750  dev  INFO: Main page was invited
INFO: 2021-05-26 19:14:09,774  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:14:25,467  dev  INFO: Main page was invited
INFO: 2021-05-26 19:14:25,495  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:15:10,575  dev  INFO: Main page was invited
INFO: 2021-05-26 19:15:10,602  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:15:50,103  dev  INFO: Main page was invited
INFO: 2021-05-26 19:15:50,127  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:16:05,188  dev  INFO: Main page was invited
INFO: 2021-05-26 19:16:05,211  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:16:28,191  dev  INFO: Main page was invited
INFO: 2021-05-26 19:16:28,227  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:18:12,108  dev  INFO: Main page was invited
INFO: 2021-05-26 19:18:12,133  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:18:26,150  dev  INFO: Main page was invited
INFO: 2021-05-26 19:18:26,175  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:19:13,209  dev  INFO: Main page was invited
INFO: 2021-05-26 19:19:13,250  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-26 19:19:44,170  dev  INFO: Main page was invited
INFO: 2021-05-26 19:19:44,223  django.request  WARNING: Not Found: /memacc/jquery.js
INFO: 2021-05-28 17:42:27,147  dev  INFO: Main page was invited
INFO: 2021-05-28 17:42:31,933  dev  INFO: Main page was invited
INFO: 2021-05-28 17:42:38,680  dev  INFO: Main page was invited
INFO: 2021-05-28 17:44:04,163  django.request  ERROR: Internal Server Error: /memacc/edit/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py", line 47, in edit
    return render(request,
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for ' ' not found. ' ' is not a valid view function or pattern name.
INFO: 2021-05-28 17:44:37,935  django.request  ERROR: Internal Server Error: /mainboard/create/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 31, in mem_create
    return render(request, 'mainboard/mem/create.html', {'section': 'mems', 'form': form})
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for ' post_list' not found. ' post_list' is not a valid view function or pattern name.
INFO: 2021-05-28 17:46:51,599  dev  INFO: Main page was invited
INFO: 2021-05-28 17:47:03,800  dev  INFO: Main page was invited
INFO: 2021-05-28 17:48:38,915  dev  INFO: Main page was invited
INFO: 2021-05-28 17:49:19,111  dev  INFO: Main page was invited
INFO: 2021-05-28 17:53:35,570  dev  INFO: Main page was invited
INFO: 2021-05-28 17:53:50,775  dev  INFO: Main page was invited
INFO: 2021-05-28 17:54:12,945  dev  INFO: Main page was invited
INFO: 2021-05-28 17:54:27,039  dev  INFO: Main page was invited
INFO: 2021-05-28 17:54:50,791  dev  INFO: Main page was invited
INFO: 2021-05-28 17:55:04,074  dev  INFO: Main page was invited
INFO: 2021-05-28 17:55:22,209  dev  INFO: Main page was invited
INFO: 2021-05-28 17:55:37,762  dev  INFO: Main page was invited
INFO: 2021-05-28 17:55:39,418  dev  INFO: Main page was invited
INFO: 2021-05-28 17:55:52,717  dev  INFO: Main page was invited
INFO: 2021-05-28 20:42:44,562  django.request  ERROR: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'socialaccount'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 35, in post_list
    return render(request, 'mainboard/post/list.html', {'mems': posts})
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'socialaccount' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
INFO: 2021-05-28 20:43:10,150  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-28 20:43:11,723  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-28 20:43:13,263  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-28 20:43:16,878  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-28 20:43:20,614  dev  INFO: Main page was invited
INFO: 2021-05-28 20:43:30,411  django.request  WARNING: Not Found: /api-auth/
INFO: 2021-05-28 20:44:12,259  dev  INFO: Main page was invited
INFO: 2021-05-28 20:44:57,567  django.request  ERROR: Internal Server Error: /memacc/api/profiles/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (7, 1998-05-26, , null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (7, 1998-05-26, , null).

INFO: 2021-05-28 20:49:15,349  django.request  ERROR: Internal Server Error: /mainboard/api/mems/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (1, mem, mem, https://memepedia.ru/khabi-lame/#post-gallery-5fac33_4, , memczik, 2021-05-28, 2021-05-28 20:49:15.305656+00, draft, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/models.py", line 34, in save
    super(Mem, self).save(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (1, mem, mem, https://memepedia.ru/khabi-lame/#post-gallery-5fac33_4, , memczik, 2021-05-28, 2021-05-28 20:49:15.305656+00, draft, null).

INFO: 2021-05-28 20:49:15,451  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-28 20:49:42,687  django.request  WARNING: Bad Request: /mainboard/api/mems/
INFO: 2021-05-28 20:49:49,963  django.request  WARNING: Bad Request: /mainboard/api/mems/
INFO: 2021-05-28 20:50:37,036  django.request  WARNING: Bad Request: /mainboard/api/mems/
INFO: 2021-05-28 20:51:03,136  django.request  WARNING: Bad Request: /mainboard/api/mems/
INFO: 2021-05-28 20:51:31,503  django.request  WARNING: Bad Request: /mainboard/api/mems/
INFO: 2021-05-28 20:51:45,351  django.request  ERROR: Internal Server Error: /mainboard/api/mems/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (2, mem, mem, https://memepedia.ru/khabi-lame/#post-gallery-5fac33_4, , , 2021-05-28, 2021-05-28 20:51:45.314146+00, draft, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/models.py", line 34, in save
    super(Mem, self).save(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (2, mem, mem, https://memepedia.ru/khabi-lame/#post-gallery-5fac33_4, , , 2021-05-28, 2021-05-28 20:51:45.314146+00, draft, null).

INFO: 2021-05-28 20:52:55,989  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/forms.py changed, reloading.
INFO: 2021-05-28 20:55:31,401  django.request  ERROR: Internal Server Error: /mainboard/create/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 22, in mem_create
    new_item = form.save(commit=False)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/forms.py", line 26, in save
    response = request.urlopen(mem_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
INFO: 2021-05-28 21:01:17,056  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-28 21:03:56,173  django.request  ERROR: Internal Server Error: /mainboard/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 35, in post_list
    return render(request, 'mainboard/post/list.html', {'mems': posts})
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_detail' with no arguments not found. 1 pattern(s) tried: ['mainboard/(?P<year>\\d{4})/(?P<month>\\d{2})/(?P<day>\\d{2})/(?P<post>[-\\w]+)/$']
INFO: 2021-05-28 21:04:10,874  django.request  ERROR: Internal Server Error: /mainboard/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 35, in post_list
    return render(request, 'mainboard/post/list.html', {'mems': posts})
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_detail' with no arguments not found. 1 pattern(s) tried: ['mainboard/(?P<year>\\d{4})/(?P<month>\\d{2})/(?P<day>\\d{2})/(?P<post>[-\\w]+)/$']
INFO: 2021-05-28 21:09:28,451  dev  INFO: Main page was invited
INFO: 2021-05-29 09:14:20,907  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:14:21,429  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:14:43,888  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 09:14:44,041  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 09:14:53,460  dev  INFO: Main page was invited
INFO: 2021-05-29 09:21:43,011  dev  INFO: Main page was invited
INFO: 2021-05-29 09:22:35,801  dev  INFO: Main page was invited
INFO: 2021-05-29 09:24:52,832  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:25:14,678  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:25:21,659  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:26:23,831  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:26:46,864  dev  INFO: Main page was invited
INFO: 2021-05-29 09:28:32,155  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:28:35,835  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:28:42,638  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:28:48,949  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:29:03,482  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-29 09:31:23,255  dev  INFO: Main page was invited
INFO: 2021-05-29 09:31:57,846  dev  INFO: Main page was invited
INFO: 2021-05-29 09:32:35,908  dev  INFO: Main page was invited
INFO: 2021-05-29 09:33:53,712  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:36:48,197  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 09:36:48,348  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 09:37:23,556  dev  INFO: Honey's profile was edited
INFO: 2021-05-29 09:37:27,918  dev  INFO: Main page was invited
INFO: 2021-05-29 09:45:52,795  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:46:17,197  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:47:15,912  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:53:25,757  dev  INFO: Main page was invited
INFO: 2021-05-29 09:53:54,040  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 09:53:56,783  dev  INFO: Main page was invited
INFO: 2021-05-29 10:15:11,924  dev  INFO: Main page was invited
INFO: 2021-05-29 10:16:09,230  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 10:16:12,253  django.security.csrf  WARNING: Forbidden (CSRF cookie not set.): /memacc/login/
INFO: 2021-05-29 10:16:35,015  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:16:35,214  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:17:04,735  dev  INFO: Main page was invited
INFO: 2021-05-29 10:17:52,695  dev  INFO: Main page was invited
INFO: 2021-05-29 10:18:55,793  django.request  ERROR: Internal Server Error: /mainboard/create/
Traceback (most recent call last):
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 22, in mem_create
    new_item = form.save(commit=False)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/forms.py", line 26, in save
    response = request.urlopen(mem_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
INFO: 2021-05-29 10:19:20,245  django.request  ERROR: Internal Server Error: /mainboard/create/
Traceback (most recent call last):
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/views.py", line 22, in mem_create
    new_item = form.save(commit=False)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/mainboard/forms.py", line 26, in save
    response = request.urlopen(mem_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
INFO: 2021-05-29 10:24:59,730  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:24:59,888  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:25:50,155  dev  INFO: Main page was invited
INFO: 2021-05-29 10:30:39,024  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:30:39,206  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:38:50,764  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:41:45,550  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:41:45,964  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 10:41:46,269  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:41:46,460  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:41:46,600  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:44:43,089  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 10:45:02,191  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:02,267  django.request  ERROR: Internal Server Error: /memacc/
Traceback (most recent call last):
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py", line 22, in dashboard
    return render(request,
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/base.py", line 479, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/template/base.py", line 496, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
INFO: 2021-05-29 10:45:12,306  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:13,416  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:13,811  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:14,089  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:14,661  dev  INFO: Main page was invited
INFO: 2021-05-29 10:45:24,641  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:45:24,846  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:45:26,449  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:03,213  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:03,264  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:03,833  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:03,867  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:04,110  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:04,135  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:04,382  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:04,416  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:04,993  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:05,020  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:09,391  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:09,932  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 10:47:11,204  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:18,729  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:47:18,914  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:47:18,944  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:47:20,388  dev  INFO: Main page was invited
INFO: 2021-05-29 10:47:20,432  django.request  WARNING: Not Found: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/static/css/style.css
INFO: 2021-05-29 10:48:21,389  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:48:21,947  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-29 10:48:24,039  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-29 10:48:27,671  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-29 10:48:27,856  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-29 10:48:27,912  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-29 10:50:00,316  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-29 10:50:02,520  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:22:02,703  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:22:02,932  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:22:07,707  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:22:09,819  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:22:32,829  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:23:58,863  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:24:05,698  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:27:21,156  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:27:23,387  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:27:24,583  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:27:27,521  dev  INFO: Main page was invited
INFO: 2021-05-30 08:27:27,565  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:27:37,738  dev  INFO: Main page was invited
INFO: 2021-05-30 08:27:37,769  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:27:40,098  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:27:53,328  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:27:54,221  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:28:21,801  dev  INFO: Main page was invited
INFO: 2021-05-30 08:28:21,838  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:28:44,955  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:28:48,295  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:28:49,926  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:28:53,338  dev  INFO: Main page was invited
INFO: 2021-05-30 08:28:53,415  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:28:55,286  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:28:57,194  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:29:08,611  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:29:09,333  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:29:36,813  dev  INFO: Main page was invited
INFO: 2021-05-30 08:29:36,842  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:29:42,070  dev  INFO: Main page was invited
INFO: 2021-05-30 08:29:42,122  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 08:30:24,811  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:31:26,709  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:33:37,152  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:33:44,313  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:33:46,957  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:33:52,053  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:34:01,560  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:34:02,334  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:38:22,909  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:39:49,732  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:40:00,767  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:40:01,706  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:41:31,660  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:41:33,366  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:41:37,543  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:42:01,346  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:42:05,132  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:42:22,218  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:43:41,883  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:43:52,901  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:44:15,468  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:44:18,076  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:44:19,706  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:45:12,820  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:46:41,469  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:47:11,072  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:47:21,337  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:47:22,132  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:48:03,167  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:48:07,431  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:48:43,657  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:48:53,289  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:48:56,072  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:49:01,408  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:50:32,531  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:51:04,472  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:51:06,718  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:51:46,867  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:51:48,483  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:53:53,827  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:54:02,481  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 08:54:04,642  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:54:20,393  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:54:21,267  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:54:22,102  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:55:04,586  django.request  ERROR: Internal Server Error: /accounts/confirm-email/Ng:1lnHDm:4MGknYWwID0V1m0uRbIBWFd-9hFYa0ANir76Z69GrsQ/
Traceback (most recent call last):
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/allauth/account/views.py", line 331, in post
    if not redirect_url:
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/utils/functional.py", line 135, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signup' not found. 'signup' is not a valid view function or pattern name.
INFO: 2021-05-30 08:55:18,051  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:55:21,764  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:55:38,863  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 08:58:08,212  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 08:58:40,470  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 08:58:41,987  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 08:58:43,642  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 09:00:22,207  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 09:05:08,816  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 09:05:15,569  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 09:05:33,731  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 09:05:36,351  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 09:05:39,892  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 09:06:05,036  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 09:06:05,991  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-30 09:07:34,264  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 09:08:00,542  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 09:08:04,060  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 09:08:10,831  dev  INFO: Main page was invited
INFO: 2021-05-30 09:08:10,869  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 09:08:12,996  django.request  WARNING: Not Found: /mainboard/style.css
INFO: 2021-05-30 09:08:15,335  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 09:09:00,931  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-30 09:09:10,676  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 09:10:33,460  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/serializers.py changed, reloading.
INFO: 2021-05-30 09:14:50,375  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/serializers.py changed, reloading.
INFO: 2021-05-30 09:14:54,044  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/serializers.py changed, reloading.
INFO: 2021-05-30 09:14:59,850  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/serializers.py changed, reloading.
INFO: 2021-05-30 09:15:33,594  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/serializers.py changed, reloading.
INFO: 2021-05-30 09:15:59,226  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 09:16:02,583  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 09:18:02,306  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-30 11:18:27,062  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 11:18:30,014  dev  INFO: Main page was invited
INFO: 2021-05-30 11:18:30,062  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 11:21:08,476  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 11:21:11,721  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 11:21:13,185  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:21:17,188  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-30 11:21:17,329  dev  INFO: Nastiona have entered into MeMes
INFO: 2021-05-30 11:21:17,352  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:21:20,595  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:21:36,514  dev  INFO: Honey's profile was edited
INFO: 2021-05-30 11:21:36,548  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:21:39,570  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:21:43,482  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-30 11:21:43,501  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 11:21:43,531  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:21:45,809  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:21:49,690  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-30 11:21:49,712  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 11:21:49,741  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:22:07,560  django.request  WARNING: Not Found: /memacc/password-reset/style.css
INFO: 2021-05-30 11:22:25,155  django.request  WARNING: Not Found: /memacc/password-reset/done/style.css
INFO: 2021-05-30 11:22:52,566  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:26:15,377  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:26:18,783  dev  INFO: Nasti Trying to enter
INFO: 2021-05-30 11:26:18,957  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:26:28,351  dev  INFO: Nasti Trying to enter
INFO: 2021-05-30 11:26:28,494  dev  INFO: Nasti have entered into MeMes
INFO: 2021-05-30 11:26:28,518  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:26:30,892  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:27:18,060  dev  ERROR: Honey's profile wasn't edited
INFO: 2021-05-30 11:27:18,094  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:27:23,661  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:27:26,324  dev  INFO: Main page was invited
INFO: 2021-05-30 11:27:26,352  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 11:27:58,523  django.request  WARNING: Not Found: /style.css
INFO: 2021-05-30 11:28:00,199  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:28:06,558  dev  INFO: Ho's profile was edited
INFO: 2021-05-30 11:28:06,615  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:28:17,374  dev  INFO: Honey's profile was edited
INFO: 2021-05-30 11:28:17,417  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:28:20,120  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:29:21,307  dev  INFO: Honey's profile was edited
INFO: 2021-05-30 11:29:21,342  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:29:24,485  django.request  WARNING: Not Found: /mainboard/create/style.css
INFO: 2021-05-30 11:29:26,102  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:29:27,986  django.request  WARNING: Not Found: /mainboard/style.css
INFO: 2021-05-30 11:29:30,847  dev  INFO: Main page was invited
INFO: 2021-05-30 11:29:30,893  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 11:29:33,665  django.request  WARNING: Not Found: /memacc/logout/style.css
INFO: 2021-05-30 11:29:35,394  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:29:39,884  dev  INFO: Nastiona Trying to enter
INFO: 2021-05-30 11:29:39,894  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 11:29:39,930  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:29:42,511  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:32:27,212  dev  INFO: Nasti Trying to enter
INFO: 2021-05-30 11:32:27,361  dev  INFO: Nasti have entered into MeMes
INFO: 2021-05-30 11:32:27,400  django.request  WARNING: Not Found: /memacc/login/style.css
INFO: 2021-05-30 11:32:36,478  django.request  WARNING: Not Found: /memacc/edit/style.css
INFO: 2021-05-30 11:32:40,881  dev  INFO: Main page was invited
INFO: 2021-05-30 11:32:40,936  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 11:32:43,045  django.request  WARNING: Not Found: /memacc/password-change/style.css
INFO: 2021-05-30 11:32:45,895  dev  INFO: Main page was invited
INFO: 2021-05-30 11:32:45,943  django.request  WARNING: Not Found: /memacc/style.css
INFO: 2021-05-30 11:33:40,830  dev  INFO: Main page was invited
INFO: 2021-05-30 11:33:45,987  dev  INFO: Main page was invited
INFO: 2021-05-30 11:54:22,770  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-30 11:59:18,458  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 11:59:21,038  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-30 11:59:40,696  django.request  WARNING: Forbidden: /memacc/api/
INFO: 2021-05-30 11:59:58,078  django.request  WARNING: Forbidden: /mainboard/api/
INFO: 2021-05-30 13:00:12,958  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:00:13,086  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:00:34,435  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:00:34,567  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:05:09,410  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:05:09,533  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:05:36,669  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:05:36,803  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:07:27,229  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:07:27,356  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:07:57,094  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:07:57,228  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:10:41,477  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:10:41,605  dev  ERROR: During the enterance error ocured
INFO: 2021-05-30 13:12:59,397  dev  INFO: mempr_user Trying to enter
INFO: 2021-05-30 13:12:59,522  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 08:24:31,276  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:24:36,684  dev  INFO: Main page was invited
INFO: 2021-05-31 08:25:48,618  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:26:31,725  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:26:33,320  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:28:08,299  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:29:20,006  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:29:42,065  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:29:45,795  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:30:24,570  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:31:25,689  django.security.csrf  WARNING: Forbidden (CSRF token missing or incorrect.): /admin/login/
INFO: 2021-05-31 08:32:04,453  dev  INFO: lll Trying to enter
INFO: 2021-05-31 08:32:35,314  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-31 08:32:42,086  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-31 08:32:44,724  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-31 08:32:58,000  dev  INFO: lll Trying to enter
INFO: 2021-05-31 08:32:58,137  dev  INFO: lll have entered into MeMes
INFO: 2021-05-31 08:38:43,274  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:42:27,015  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:43:08,123  django.security.csrf  WARNING: Forbidden (CSRF token missing or incorrect.): /memacc/login/
INFO: 2021-05-31 08:43:29,489  dev  INFO: lll Trying to enter
INFO: 2021-05-31 08:43:29,642  dev  INFO: lll have entered into MeMes
INFO: 2021-05-31 08:43:46,107  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:43:56,034  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:44:10,797  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:44:33,032  django.request  ERROR: Internal Server Error: /accounts/google/login/callback/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 147, in dispatch
    return complete_social_login(request, login)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/socialaccount/helpers.py", line 151, in complete_social_login
    return _complete_social_login(request, sociallogin)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/socialaccount/helpers.py", line 166, in _complete_social_login
    ret = _login_social_account(request, sociallogin)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/socialaccount/helpers.py", line 48, in _login_social_account
    return perform_login(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/utils.py", line 180, in perform_login
    get_login_redirect_url(request, redirect_url, signup=signup)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/utils.py", line 62, in get_login_redirect_url
    ret = get_adapter(request).get_login_redirect_url(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/adapter.py", line 157, in get_login_redirect_url
    return resolve_url(url)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/shortcuts.py", line 122, in resolve_url
    to = str(to)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_password' not found. 'set_password' is not a valid view function or pattern name.
INFO: 2021-05-31 08:44:56,091  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 08:45:22,675  dev  INFO: Main page was invited
INFO: 2021-05-31 08:46:09,977  dev  INFO: lll Trying to enter
INFO: 2021-05-31 08:46:10,122  dev  INFO: lll have entered into MeMes
INFO: 2021-05-31 08:48:04,935  django.request  WARNING: Not Found: /favicon.ico
INFO: 2021-05-31 08:48:13,505  django.request  ERROR: Internal Server Error: /accounts/password/set/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 644, in dispatch
    return super(PasswordSetView, self).dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 670, in get_context_data
    ret = super(PasswordSetView, self).get_context_data(**kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 112, in get_form
    form = super(AjaxCapableProcessFormViewMixin, self).get_form(form_class)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
TypeError: __init__() got an unexpected keyword argument 'user'
INFO: 2021-05-31 08:49:20,237  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:50:36,605  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-31 08:50:41,281  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/views.py changed, reloading.
INFO: 2021-05-31 08:51:09,656  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:51:14,360  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:52:55,211  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:52:58,835  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:53:02,961  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:53:12,800  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memacc/forms.py changed, reloading.
INFO: 2021-05-31 08:53:21,443  django.security.csrf  WARNING: Forbidden (CSRF token missing or incorrect.): /accounts/social/signup/
INFO: 2021-05-31 08:53:29,782  django.security.csrf  WARNING: Forbidden (CSRF token missing or incorrect.): /accounts/social/signup/
INFO: 2021-05-31 08:53:36,340  django.request  ERROR: Internal Server Error: /accounts/password/set/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 644, in dispatch
    return super(PasswordSetView, self).dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 670, in get_context_data
    ret = super(PasswordSetView, self).get_context_data(**kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 112, in get_form
    form = super(AjaxCapableProcessFormViewMixin, self).get_form(form_class)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
TypeError: __init__() got an unexpected keyword argument 'user'
INFO: 2021-05-31 08:53:49,580  dev  INFO: Main page was invited
INFO: 2021-05-31 08:54:25,976  dev  INFO: name Trying to enter
INFO: 2021-05-31 08:54:25,985  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 08:54:31,772  django.request  ERROR: Internal Server Error: /accounts/password/set/
Traceback (most recent call last):
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 644, in dispatch
    return super(PasswordSetView, self).dispatch(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 670, in get_context_data
    ret = super(PasswordSetView, self).get_context_data(**kwargs)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/allauth/account/views.py", line 112, in get_form
    form = super(AjaxCapableProcessFormViewMixin, self).get_form(form_class)
  File "/home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlifeenv/lib/python3.8/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
TypeError: __init__() got an unexpected keyword argument 'user'
INFO: 2021-05-31 09:02:34,486  django.utils.autoreload  INFO: /home/nastiona/Universe/2course/ISP/Python/third_lab/Mem/memlife/memlife/settings.py changed, reloading.
INFO: 2021-05-31 09:20:11,315  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:20:11,447  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:25:18,267  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:25:18,388  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:49:35,766  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:49:35,770  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:50:12,268  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:50:12,271  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:53:07,375  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:53:07,379  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:53:27,953  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:53:27,958  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:53:51,901  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:53:51,905  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:53:51,922  dev  INFO: 1_user Trying to enter
INFO: 2021-05-31 09:53:51,925  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:54:52,205  dev  INFO: _user Trying to enter
INFO: 2021-05-31 09:54:52,208  dev  ERROR: During the enterance error ocured
INFO: 2021-05-31 09:54:52,224  dev  INFO: 1_user Trying to enter
INFO: 2021-05-31 09:54:52,227  dev  ERROR: During the enterance error ocured
